Repository wanted-wecode-subjects/redbrick-subject, pull requests merged in 2021-11, with the labels that each got.

#18 chore: 초기 설정
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/core/entities/core.entity.ts
  src/main.ts
Labels: chore

#20 chore: 게임 초기 설정
  src/app.module.ts
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.repository.ts
  src/game/game.service.ts
Labels: chore

#21 PR 템플릿 적용으로 main 릴리즈
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  src/app.module.ts
  src/core/entities/core.entity.ts
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.repository.ts
  src/game/game.service.ts
  src/main.ts
Labels: chore

#31 feat: 게임 상세 조회
  src/game/game.controller.ts
  src/game/game.service.ts
Labels: feat

#28 feat:user모듈생성, dto생성, entity생성
  src/app.module.ts
  src/game/dto/create-game.dto.ts
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.repository.ts
  src/game/game.service.ts
  src/users/dto/create-user.dto.ts
  src/users/dto/update-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: chore

#37 fix: 파일 복구
  src/game/dto/create-game.dto.ts
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.repository.ts
  src/game/game.service.ts
Labels: fix

#38 feat: 게임 수정
  src/game/dto/update-game.dto.ts
  src/game/game.controller.ts
  src/game/game.service.ts
Labels: feat

#35 feat: 게임 삭제
  src/game/game.controller.ts
  src/game/game.service.ts
Labels: feat

#34 feat: 게임 전체 조회
  src/game/game.controller.ts
  src/game/game.service.ts
Labels: feat

#36 feat: project crud
  package-lock.json
  package.json
  src/app.module.ts
  src/projects/dto/create-project.dto.ts
  src/projects/dto/update-project.dto.ts
  src/projects/entities/project.entity.ts
  src/projects/projects.controller.ts
  src/projects/projects.interface.ts
  src/projects/projects.module.ts
  src/projects/projects.service.ts
Labels: feat

#40 fix: 게임 상세 조회 버그 수정
  src/game/game.service.ts
Labels: bug

#42 feat: project, game 조인
  src/game/dto/create-game.dto.ts
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.repository.ts
  src/game/game.service.ts
  src/projects/projects.module.ts
Labels: feat

#49 fix: user create
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: bug, fix

#51 feat:유저 수정 기능추가(비밀번호, 닉네임 변경 기능)
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: feat

#54 feat: 게임 좋아요 및 게임 좋아요 취소
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.repository.ts
  src/game/game.service.ts
  src/users/entities/user.entity.ts
Labels: feat

#52 feat: game-user 연결
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.repository.ts
  src/game/game.service.ts
  src/users/entities/user.entity.ts
Labels: feat

#53 feat: project & user 조인
  src/projects/dto/create-project.dto.ts
  src/projects/entities/project.entity.ts
  src/projects/projects.controller.ts
  src/projects/projects.service.ts
  src/users/entities/user.entity.ts
Labels: feat

#55 Feature/user logout
  src/auth/auth.controller.ts
  src/auth/auth.service.ts
  src/users/entities/user.entity.ts
  src/users/users.service.ts
Labels: feat, fix

#59 feat: 게임 전체 및 상세 조회때 좋아요 숫자와 리스트 출력
  src/game/entities/game.entity.ts
  src/game/game.controller.ts
  src/game/game.repository.ts
  src/game/game.service.ts
Labels: feat

#57 feat: project publish
  src/app.module.ts
  src/game/dto/update-game.dto.ts
  src/game/game.controller.ts
  src/game/game.module.ts
  src/game/game.service.ts
  src/projects/dto/publish-project.dto.ts
  src/projects/projects.controller.ts
  src/projects/projects.interface.ts
  src/projects/projects.module.ts
Labels: feat

#63 feat: game search
  src/game/game.controller.ts
  src/game/game.service.ts
Labels: feat

#64 refactor: 게임 전체 및 상세 조회
  src/game/game.repository.ts
Labels: refactoring

#73 chore: heroku 배포 설정
  Procfile
Labels: chore

#72 test: game service 유닛 테스트
  src/game/game.controller.ts
  src/game/game.service.spec.ts
Labels: test

#75 fix: project unit test
  src/projects/projects.service.spec.ts
  src/projects/projects.service.ts
Labels: bug, fix
